# See documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - skip: true
release:
  github:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
